name       : upx
version    : 4.0.0
release    : 4
source     :
    - https://github.com/upx/upx/releases/download/v4.0.0/upx-4.0.0-src.tar.xz : eaf938f8824e65f06852142fda97f8349ad660612979fa311618109c819f36ea
license    : GPL-2.0-or-later
component  : system.utils
summary    : Ultimate Packer for eXecutables.
description: |
    Free, portable, extendable, high-performance executable packer for several executable formats. UPX achieves an excellent compression ratio and offers very fast decompression. Your executables suffer no memory overhead or other drawbacks for most of the formats supported, because of in-place decompression.
build      : |
    %make
install    : |
    install -Dm0755 build/release/upx $installdir/usr/bin/upx
    install -Dm0644 doc/upx.1 $installdir/usr/share/man/man1/upx.1
