name       : upx
version    : 3.96
release    : 3
source     :
    - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-src.tar.xz : 47774df5c958f2868ef550fb258b97c73272cb1f44fe776b798e393465993714
license    : GPL-2.0-or-later
component  : system.utils
summary    : Ultimate Packer for eXecutables.
description: |
    Free, portable, extendable, high-performance executable packer for several executable formats. UPX achieves an excellent compression ratio and offers very fast decompression. Your executables suffer no memory overhead or other drawbacks for most of the formats supported, because of in-place decompression.
builddeps  :
    - ucl-devel
build      : |
    %make all
install    : |
    install -Dm0755 src/upx.out $installdir/usr/bin/upx
    install -Dm0644 doc/upx.1 $installdir/usr/share/man/man1/upx.1
